### ISSUE TITLE
Why override outline for gray background instead of using background-color of `.custom-dialog[opened]`

### ISSUE THREAD

**Issue by lozandier** [PolymerLabs/building-custom-overlays#1]
For the sake of curiosity, why the following wasn't considered
```css
.custom-dialog[opened] {
  background: rgba(0, 0, 0, 0.1);
}
````

instead of 

```css
.content-wrapper {
  outline: 9999px solid rgba(0, 0, 0, 0.1);
}
```

Merely adding an additional `9` breaks the existing code which seems eccentric to say the least.

If `outline` is insisted on being used for a background purpose, how come a value such as `100vmax` wasn't used instead to ensure no issues with finite values associated with the ultimate purpose of ensuring the entire viewport is considered to have a visual background that in fact always cover it? 

It seemingly should have a comment nonetheless.
